- hosts: auditing-server-machine
  vars:
    deploy_script_runner: bash -x deploy-script.sh
    server_dir: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-atm-components/auditing-server"
  tasks:
    - name: Deploy auditing server
      shell: "{{ deploy_script_runner }}"
      become: yes
      args:
        chdir: "{{ server_dir }}"