#!/bin/bash

CONF_FILE_SOURCE_DIR="$(pwd)/conf-files"
SERVER_CONF_FILE_NAME="auditing-server.conf"
SERVICES_CONF_FILE_NAME="services.conf"
CONF_FILE_DEST_DIR="services/auditing-server"
SECRETS_FILE="secrets"

yes | cp -f $CONF_FILE_SOURCE_DIR/SERVER_CONF_FILE_NAME $CONF_FILE_DEST_DIR
yes | cp -f $CONF_FILE_SOURCE_DIR/SECRETS_FILE $CONF_FILE_DEST_DIR
yes | cp -f $CONF_FILE_SOURCE_DIR/$SERVICES_CONF_FILE_NAME $CONF_FILE_DEST_DIR