---
- hosts: auditing-client-machine
  vars:
    deploy_script_runner: bash deploy-script.sh
    client_dir: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-atm-components/auditing-client"
  tasks:
    - name: Deploy auditing client
      shell: "{{ deploy_script_runner }}"
      become: yes
      args:
        chdir: "{{ client_dir }}"

- hosts: probes-machine
  vars:
    deploy_script_runner: bash deploy-script.sh
    probes_dir: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-atm-components/probes"
  tasks:
    - name: Deploy probes
      shell: "{{ deploy_script_runner }}"
      become: yes
      args:
        chdir: "{{ probes_dir }}"
