---
- hosts: localhost
  vars:
    script_runner: bash -x start-env-composers.sh
    script_path: ../../scripts/probes-auditing-client
  tasks:
    - name: Setting up configuration files
      shell: "{{ script_runner }}"
      args:
        chdir: "{{ script_path }}"