---
- hosts: probes-machine
  vars:
    probes_dir: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-atm-components/probes/"
  tasks:
    - name: Removing probes
      become: yes
      file:
        state: absent
        path: "{{ probes_dir }}"

- hosts: auditing-client-machine
  vars:
    client_dir: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-atm-components/auditing-client/"
  tasks:
    - name: Removing auditing client
      become: yes
      file:
        state: absent
        path: "{{ client_dir }}"

- hosts: auditing-server-machine
  vars:
    server_dir: "/home/{{ lookup('config', 'DEFAULT_REMOTE_USER')}}/fogbow-atm-components/auditing-server/"
  tasks:
    - name: Removing auditing server
      become: yes
      file:
        state: absent
        path: "{{ server_dir }}"