#!/bin/bash
DIR=$(pwd)
CONF_FILES_DIR=../../"conf-files"
SECRETS_FILE_PATH=$CONF_FILES_DIR/"secrets"

DB_PASSWORD_PROPERTY="db_password"

touch $SECRETS_FILE_PATH
chmod 600 $SECRETS_FILE_PATH

# Fill passwords
GENERATED_PASSWORD=$(pwgen 10 1)
echo "$DB_PASSWORD_PROPERTY=$GENERATED_PASSWORD" >| $SECRETS_FILE_PATH