#!/bin/bash

CONF_FILE_SOURCE_DIR="$(pwd)/conf-files"
PROBES_CONF_FILE_NAME="probes.conf"
SERVICES_CONF_FILE_NAME="services.conf"
CONF_FILE_DEST_DIR="services/probes"

yes | cp -f $CONF_FILE_SOURCE_DIR/$PROBES_CONF_FILE_NAME $CONF_FILE_DEST_DIR
yes | cp -f $CONF_FILE_SOURCE_DIR/$SERVICES_CONF_FILE_NAME $CONF_FILE_DEST_DIR